version: "3.7"

services:
  authservice:
    build: ./AuthService
    ports:
      - 8080:5000
    environment:
      PORT: 5000
      MONGO_URI: "mongodb://${DB_USER}:${DB_PSWD}@mongodb/quiz_app"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PSWD}
      MONGO_INITDB_DATABASE: quiz_app
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
